// <auto-generated />
using System;
using AvangersDietApp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvangersDietApp.DAL.Migrations
{
    [DbContext(typeof(AvangersContext))]
    [Migration("20240119131707_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Et"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Meyve"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Sebze ve Bakliyat"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Atıştırmalık"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Süt Ürünleri"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Diğer Ürünler"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Unlu Ürünler"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Tatlılar"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Çerez ve Kuru Yemiş"
                        });
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<int?>("FoodStrategyId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Proteins")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FoodStrategyId");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 289.0,
                            Carbohydrates = 0.0,
                            CategoryId = 5,
                            Fats = 4.4000000000000004,
                            Name = "Kaşar peynir",
                            Proteins = 22.5
                        },
                        new
                        {
                            Id = 2,
                            Calories = 61.0,
                            Carbohydrates = 4.7000000000000002,
                            CategoryId = 5,
                            Fats = 3.2999999999999998,
                            Name = "Yoğurt",
                            Proteins = 3.5
                        },
                        new
                        {
                            Id = 3,
                            Calories = 158.0,
                            Carbohydrates = 0.0,
                            CategoryId = 6,
                            Fats = 11.199999999999999,
                            Name = "Yumurta",
                            Proteins = 12.1
                        },
                        new
                        {
                            Id = 4,
                            Calories = 207.0,
                            Carbohydrates = 0.0,
                            CategoryId = 6,
                            Fats = 4.4000000000000004,
                            Name = "Siyah Zeytin",
                            Proteins = 0.14999999999999999
                        },
                        new
                        {
                            Id = 5,
                            Calories = 25.0,
                            Carbohydrates = 4.0,
                            CategoryId = 3,
                            Fats = 0.29999999999999999,
                            Name = "Domates",
                            Proteins = 1.0
                        },
                        new
                        {
                            Id = 6,
                            Calories = 8.0,
                            Carbohydrates = 1.0,
                            CategoryId = 3,
                            Fats = 0.0,
                            Name = "Salatalık",
                            Proteins = 1.0
                        },
                        new
                        {
                            Id = 7,
                            Calories = 26.0,
                            Carbohydrates = 0.59999999999999998,
                            CategoryId = 3,
                            Fats = 0.10000000000000001,
                            Name = "Kabak",
                            Proteins = 1.0
                        },
                        new
                        {
                            Id = 8,
                            Calories = 25.0,
                            Carbohydrates = 3.2000000000000002,
                            CategoryId = 3,
                            Fats = 0.29999999999999999,
                            Name = "Ispanak",
                            Proteins = 2.2999999999999998
                        },
                        new
                        {
                            Id = 9,
                            Calories = 25.0,
                            Carbohydrates = 4.9000000000000004,
                            CategoryId = 3,
                            Fats = 0.20000000000000001,
                            Name = "Karnabahar",
                            Proteins = 2.3999999999999999
                        },
                        new
                        {
                            Id = 10,
                            Calories = 24.0,
                            Carbohydrates = 5.2999999999999998,
                            CategoryId = 3,
                            Fats = 0.20000000000000001,
                            Name = "Lahana",
                            Proteins = 1.3999999999999999
                        },
                        new
                        {
                            Id = 11,
                            Calories = 351.0,
                            Carbohydrates = 57.399999999999999,
                            CategoryId = 5,
                            Fats = 1.3,
                            Name = "Mercimek",
                            Proteins = 23.699999999999999
                        },
                        new
                        {
                            Id = 12,
                            Calories = 376.0,
                            Carbohydrates = 56.700000000000003,
                            CategoryId = 3,
                            Fats = 6.2000000000000002,
                            Name = "Nohut",
                            Proteins = 19.199999999999999
                        },
                        new
                        {
                            Id = 13,
                            Calories = 63.0,
                            Carbohydrates = 11.9,
                            CategoryId = 3,
                            Fats = 0.40000000000000002,
                            Name = "Enginar",
                            Proteins = 2.8999999999999999
                        },
                        new
                        {
                            Id = 14,
                            Calories = 52.0,
                            Carbohydrates = 13.0,
                            CategoryId = 3,
                            Fats = 0.20000000000000001,
                            Name = "Pırasa",
                            Proteins = 1.8
                        },
                        new
                        {
                            Id = 15,
                            Calories = 42.0,
                            Carbohydrates = 4.0,
                            CategoryId = 3,
                            Fats = 0.10000000000000001,
                            Name = "Bamya",
                            Proteins = 6.0
                        },
                        new
                        {
                            Id = 16,
                            Calories = 122.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 3.0,
                            Name = "Tavuk-but",
                            Proteins = 21.0
                        },
                        new
                        {
                            Id = 17,
                            Calories = 104.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 1.0,
                            Name = "Tavuk-göğüs",
                            Proteins = 23.0
                        },
                        new
                        {
                            Id = 18,
                            Calories = 160.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 8.0,
                            Name = "Hindi",
                            Proteins = 20.399999999999999
                        },
                        new
                        {
                            Id = 19,
                            Calories = 170.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 3.6000000000000001,
                            Name = "Dana kıyma yağlı",
                            Proteins = 20.0
                        },
                        new
                        {
                            Id = 20,
                            Calories = 156.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 8.0,
                            Name = "Dana Eti",
                            Proteins = 19.699999999999999
                        },
                        new
                        {
                            Id = 21,
                            Calories = 450.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 38.100000000000001,
                            Name = "Salam",
                            Proteins = 23.399999999999999
                        },
                        new
                        {
                            Id = 22,
                            Calories = 452.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 21.399999999999999,
                            Name = "Sucuk",
                            Proteins = 21.399999999999999
                        },
                        new
                        {
                            Id = 23,
                            Calories = 370.0,
                            Carbohydrates = 75.200000000000003,
                            CategoryId = 7,
                            Fats = 1.2,
                            Name = "Makarna",
                            Proteins = 12.5
                        },
                        new
                        {
                            Id = 24,
                            Calories = 452.0,
                            Carbohydrates = 0.0,
                            CategoryId = 7,
                            Fats = 21.399999999999999,
                            Name = "Pirinç",
                            Proteins = 21.399999999999999
                        },
                        new
                        {
                            Id = 25,
                            Calories = 357.0,
                            Carbohydrates = 78.099999999999994,
                            CategoryId = 7,
                            Fats = 1.2,
                            Name = "Bulgur",
                            Proteins = 10.300000000000001
                        },
                        new
                        {
                            Id = 26,
                            Calories = 247.0,
                            Carbohydrates = 53.100000000000001,
                            CategoryId = 7,
                            Fats = 1.1000000000000001,
                            Name = "Buğday Ekmeği",
                            Proteins = 7.2000000000000002
                        },
                        new
                        {
                            Id = 27,
                            Calories = 315.0,
                            Carbohydrates = 78.400000000000006,
                            CategoryId = 8,
                            Fats = 0.0,
                            Name = "Bal",
                            Proteins = 0.29999999999999999
                        },
                        new
                        {
                            Id = 28,
                            Calories = 550.0,
                            Carbohydrates = 51.299999999999997,
                            CategoryId = 8,
                            Fats = 36.0,
                            Name = "Çikolata",
                            Proteins = 9.3000000000000007
                        },
                        new
                        {
                            Id = 29,
                            Calories = 275.0,
                            Carbohydrates = 70.0,
                            CategoryId = 8,
                            Fats = 0.5,
                            Name = "Marmelat ve Reçel",
                            Proteins = 0.59999999999999998
                        },
                        new
                        {
                            Id = 30,
                            Calories = 173.0,
                            Carbohydrates = 29.800000000000001,
                            CategoryId = 8,
                            Fats = 3.7999999999999998,
                            Name = "Muhallebi",
                            Proteins = 5.0999999999999996
                        },
                        new
                        {
                            Id = 31,
                            Calories = 140.0,
                            Carbohydrates = 38.0,
                            CategoryId = 8,
                            Fats = 2.7000000000000002,
                            Name = "Sütlaç",
                            Proteins = 3.3999999999999999
                        },
                        new
                        {
                            Id = 32,
                            Calories = 600.0,
                            Carbohydrates = 19.800000000000001,
                            CategoryId = 9,
                            Fats = 54.200000000000003,
                            Name = "Badem",
                            Proteins = 18.600000000000001
                        },
                        new
                        {
                            Id = 33,
                            Calories = 650.0,
                            Carbohydrates = 15.800000000000001,
                            CategoryId = 9,
                            Fats = 64.0,
                            Name = "Ceviz",
                            Proteins = 15.0
                        },
                        new
                        {
                            Id = 34,
                            Calories = 634.0,
                            Carbohydrates = 16.800000000000001,
                            CategoryId = 9,
                            Fats = 62.399999999999999,
                            Name = "Fındık",
                            Proteins = 12.6
                        },
                        new
                        {
                            Id = 35,
                            Calories = 600.0,
                            Carbohydrates = 19.0,
                            CategoryId = 9,
                            Fats = 54.0,
                            Name = "Şam Fıstığı",
                            Proteins = 19.5
                        },
                        new
                        {
                            Id = 36,
                            Calories = 289.0,
                            Carbohydrates = 0.0,
                            CategoryId = 5,
                            Fats = 4.4000000000000004,
                            Name = "Beyaz peynir",
                            Proteins = 22.5
                        },
                        new
                        {
                            Id = 37,
                            Calories = 58.0,
                            Carbohydrates = 15.0,
                            CategoryId = 2,
                            Fats = 0.59999999999999998,
                            Name = "Elma",
                            Proteins = 0.20000000000000001
                        },
                        new
                        {
                            Id = 38,
                            Calories = 61.0,
                            Carbohydrates = 15.300000000000001,
                            CategoryId = 2,
                            Fats = 0.40000000000000002,
                            Name = "Armut",
                            Proteins = 0.69999999999999996
                        },
                        new
                        {
                            Id = 39,
                            Calories = 37.0,
                            Carbohydrates = 8.4000000000000004,
                            CategoryId = 2,
                            Fats = 0.5,
                            Name = "Çilek",
                            Proteins = 0.69999999999999996
                        },
                        new
                        {
                            Id = 40,
                            Calories = 80.0,
                            Carbohydrates = 20.399999999999999,
                            CategoryId = 2,
                            Fats = 0.40000000000000002,
                            Name = "İncir",
                            Proteins = 1.2
                        },
                        new
                        {
                            Id = 41,
                            Calories = 51.0,
                            Carbohydrates = 12.9,
                            CategoryId = 2,
                            Fats = 0.20000000000000001,
                            Name = "Kayısı",
                            Proteins = 1.0
                        },
                        new
                        {
                            Id = 42,
                            Calories = 70.0,
                            Carbohydrates = 17.399999999999999,
                            CategoryId = 2,
                            Fats = 0.29999999999999999,
                            Name = "Kiraz",
                            Proteins = 1.3
                        },
                        new
                        {
                            Id = 43,
                            Calories = 50.0,
                            Carbohydrates = 12.300000000000001,
                            CategoryId = 2,
                            Fats = 0.20000000000000001,
                            Name = "Portakal",
                            Proteins = 1.0
                        },
                        new
                        {
                            Id = 44,
                            Calories = 85.0,
                            Carbohydrates = 9.6999999999999993,
                            CategoryId = 2,
                            Fats = 0.20000000000000001,
                            Name = "Şeftali",
                            Proteins = 0.59999999999999998
                        },
                        new
                        {
                            Id = 45,
                            Calories = 50.0,
                            Carbohydrates = 11.6,
                            CategoryId = 2,
                            Fats = 0.20000000000000001,
                            Name = "Muz",
                            Proteins = 1.1000000000000001
                        },
                        new
                        {
                            Id = 46,
                            Calories = 168.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 7.2999999999999998,
                            Name = "Palamut",
                            Proteins = 24.0
                        },
                        new
                        {
                            Id = 47,
                            Calories = 168.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 10.0,
                            Name = "Alabalık",
                            Proteins = 18.300000000000001
                        },
                        new
                        {
                            Id = 48,
                            Calories = 93.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 1.2,
                            Name = "Levrek",
                            Proteins = 19.199999999999999
                        },
                        new
                        {
                            Id = 49,
                            Calories = 159.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 7.2999999999999998,
                            Name = "Uskumru",
                            Proteins = 21.899999999999999
                        },
                        new
                        {
                            Id = 50,
                            Calories = 168.0,
                            Carbohydrates = 0.0,
                            CategoryId = 1,
                            Fats = 7.2999999999999998,
                            Name = "Palamut",
                            Proteins = 24.0
                        });
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.FoodStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FoodStrategy");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calorie")
                        .HasColumnType("float");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MealTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Meal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.UserMealFood", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "MealId", "FoodId");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("UserMealFoods");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.SubClasses.Breakfast", b =>
                {
                    b.HasBaseType("AvangersDietApp.DAL.Concrate.Meal");

                    b.HasDiscriminator().HasValue("Breakfast");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.SubClasses.Dinner", b =>
                {
                    b.HasBaseType("AvangersDietApp.DAL.Concrate.Meal");

                    b.HasDiscriminator().HasValue("Dinner");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.SubClasses.Lunch", b =>
                {
                    b.HasBaseType("AvangersDietApp.DAL.Concrate.Meal");

                    b.HasDiscriminator().HasValue("Lunch");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.SubClasses.Snack", b =>
                {
                    b.HasBaseType("AvangersDietApp.DAL.Concrate.Meal");

                    b.HasDiscriminator().HasValue("Snack");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.Food", b =>
                {
                    b.HasOne("AvangersDietApp.DAL.Concrate.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvangersDietApp.DAL.Concrate.FoodStrategy", null)
                        .WithMany("Foodlist")
                        .HasForeignKey("FoodStrategyId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.UserMealFood", b =>
                {
                    b.HasOne("AvangersDietApp.DAL.Concrate.Food", "Food")
                        .WithMany("UserMealFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvangersDietApp.DAL.Concrate.Meal", "Meal")
                        .WithMany("UserMealFoods")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvangersDietApp.DAL.Concrate.User", "User")
                        .WithMany("UserMealFoods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.Food", b =>
                {
                    b.Navigation("UserMealFoods");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.FoodStrategy", b =>
                {
                    b.Navigation("Foodlist");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.Meal", b =>
                {
                    b.Navigation("UserMealFoods");
                });

            modelBuilder.Entity("AvangersDietApp.DAL.Concrate.User", b =>
                {
                    b.Navigation("UserMealFoods");
                });
#pragma warning restore 612, 618
        }
    }
}
